### ISSUE TITLE
`extra-build-dependencies` docs example is wrong

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#15124]
The example rendering for `extra-build-dependencies` is wrong at https://docs.astral.sh/uv/reference/settings/#extra-build-dependencies:

<img width="1063" height="670" alt="Image" src="https://github.com/user-attachments/assets/c932c14f-4752-4a48-b90f-21c7c7e691ec" />

**Comment by zanieb** [comment]
What.. I thought I fixed this. I guess not though, thanks!

**Comment by zanieb** [comment]
@konstin what's up? This was fixed in a subsequent commit.

**Comment by konstin** [comment]
It doesn't seems partially fixed, but not in all locations:

https://docs.astral.sh/uv/reference/settings/#pip_extra-build-dependencies

<img width="1058" height="649" alt="Image" src="https://github.com/user-attachments/assets/94ce821c-8d8d-483a-ad70-370138328395" />

https://docs.astral.sh/uv/reference/settings/#extra-build-dependencies

<img width="1058" height="649" alt="Image" src="https://github.com/user-attachments/assets/2d357e52-9616-4446-8f88-76e171a783df" />

I'm not fully following with the revert, but I can see those two cases on main.
