### ISSUE TITLE
uv powershell windows only works if you are running powershell as admin

### ISSUE THREAD

**Issue by Chris2L** [astral-sh/uv#3116]
Trying to run uv using VS code on windows.  Install uv on powershell using command 
`powershell -c "irm https://astral.sh/uv/install.ps1 | iex"`
This installs version 0.1.33

If I try to create venv running command:
`uv venv`
powershell responds with 

> uv : The term 'uv' is not recognized as the name of a cmdlet, function, script file, or operable program.

If I install and run powershell as admin, it seems to work fine while still in admin.  This should not be the way to use it as running things with admin should be reserved to extreme cases. 

Running windows 11

**Comment by charliermarsh** [comment]
Ahh sorry, I think this might be the same as https://github.com/axodotdev/cargo-dist/issues/833? We're tracking it over in `cargo-dist`.

**Comment by mattharrison** [comment]
I ran into this issue as well on my Windows 10 machine. uv installed (or appeared to without error) but I get the following message:

```
PS C:\Users\matt> uv
uv : The term 'uv' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ uv
+ ~~
    + CategoryInfo          : ObjectNotFound: (uv:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by cOborski** [comment]
> I ran into this issue as well on my Windows 10 machine. uv installed (or appeared to without error) but I get the following message:
> 
> ```
> PS C:\Users\matt> uv
> uv : The term 'uv' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
> spelling of the name, or if a path was included, verify that the path is correct and try again.
> At line:1 char:1
> + uv
> + ~~
>     + CategoryInfo          : ObjectNotFound: (uv:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> ```

I was getting the same error--long story short, `sudo powershell -ExecutionPolicy Bypass -c "pip install uv"` ended up working.

I'm running gsudo in powershell on windows 11.

**Comment by Sairam90** [comment]
![image](https://github.com/user-attachments/assets/530d58e9-9d8a-4295-941e-bcb0582727d0)
Could someone confirm if this also related to the same issue ?..I am unable to run uv commands as admin as well on powershell/Command Prompt/GitBash

**Comment by Scylla2020** [comment]
So there is no solution to this yet? Thought i finally found a way to set up python for clients in a straightforward way on windows but no still hard

**Comment by Scylla2020** [comment]
Thanks will try that

**Comment by vinay-jose** [comment]
> Just check after a reboot if it is still an issue. I installed it again a few weeks ago, and it only started to work after logging out or rebooting. Basically, the PATH variable needs to be reloaded. I hope it helps. I'm enjoying UV so far!

This works. Thank you!

**Comment by g1331** [comment]
> Just check after a reboot if it is still an issue. I installed it again a few weeks ago, and it only started to work after logging out or rebooting. Basically, the PATH variable needs to be reloaded. I hope it helps. I'm enjoying UV so far!

When it happened, I found a lot of ways to solve it, and then I remembered that the easiest reboot was solved. ;)

**Comment by Jayanth-MKV** [comment]
If any of the steps given in the official docs and the above works 😟, then try these 👇

## This worked for me

- **Install via pip**:
  If issues persist, consider installing `uv` directly using pip:

  ```powershell
  powershell -ExecutionPolicy Bypass -c "pip install uv"
  ```

  This command bypasses the execution policy temporarily just for this command and installs `uv` globally.

**Comment by zanieb** [comment]
You shouldn't need admin access, did you install it as an admin? did you reboot? is it on your `PATH`?

**Comment by raminmardani** [comment]
powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"

**Comment by huni1023** [comment]
I have the same issue too,
For me solution @CodenameCookie, @raminmardani suggested worked.
But my firewall software ("AhnLab V3 Lite") blocks install, I have to shutdown firewall while installing. Thkx!

**Comment by fire-mirror** [comment]
I have same trouble,that I only can use uv in cmd and directort C: .I have add the path into systemic environment path After uninstall uv,I even can`t install uv with powershell command "powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"



![Image](https://github.com/user-attachments/assets/ff6503af-4e1e-467c-bb81-75c4d794865f)
修改：After I use vpn,I success install ,but still can`t use uv

![Image](https://github.com/user-attachments/assets/80432b3b-bc9c-4c9c-b4f4-95f9e7612d4e)
In fact,I can use uv when I in cmd,but can`t in powershell

![Image](https://github.com/user-attachments/assets/88dd171b-35f8-4e5b-bf8f-bdd17d569229)
My powershell ExecutionPolicy is RemoteSigned

**Comment by fire-mirror** [comment]
> If any of the steps given in the official docs and the above works 😟, then try these 👇如果官方文档中给出的步骤和上面的步骤都无效 😟，那么请尝试以下这些 👇
> 
> ## This worked for me
> 这对我有效
> * **Install via pip**:  使用 pip 进行安装：
>   If issues persist, consider installing `uv` directly using pip:如果问题仍然存在，请考虑直接使用 pip 安装 `uv` ：
>   powershell -ExecutionPolicy Bypass -c "pip install uv"
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   This command bypasses the execution policy temporarily just for this command and installs `uv` globally.此命令临时绕过执行策略，仅为此命令安装 `uv` 全局。

when use pip install uv,where it will install?

**Comment by wyattscarpenter** [comment]
Maybe not the same problem, but I got the same error message under discussion (uv not found on the command line), for which this is the first google result for me, on Windows 11 when I installed python from the windows store and then used its pip to install uv. Turns out that doesn't really work! So, if you're also getting this error message and the other fixes don't work for you, try installing python from the python website instead, I guess.

**Comment by humbberto** [comment]
> I think I'm having this issue too. I installed it globally with this line but PowerShell doesn't seem to have access to UV unless in admin mode. Which isn't ideal for me. Bit of a security issue. `powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex`

this actually fixed the issue on my end

tks a lot @CodenameCookie

**Comment by ShivaniGole** [comment]
> in windows: `powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"`
> 
> then close your powershell and open a new one `uv ` will work after

this worked eventually. thanks @raminmardani
